-- =============================================================================
-- 1. Add subcategory column (used to group strength exercises in the picker)
-- =============================================================================
alter table exercises
  add column if not exists subcategory text;

-- =============================================================================
-- 2. Clear the existing library and everything that references it.
--    DESTRUCTIVE — wipes assigned_exercises and exercise_logs too because the
--    exercises FK is ON DELETE RESTRICT. If you have programmes you want to
--    keep, comment out the three delete statements below before running.
-- =============================================================================
delete from exercise_logs;
delete from assigned_exercises;
delete from exercises;

-- =============================================================================
-- 3. Bulk insert the WIO movement library.
--    - URLs that were obviously truncated in the source sheet are stored NULL.
--    - Duplicates by name are de-duplicated (first occurrence wins).
--    - Strength exercises carry a subcategory (chest / shoulders / arms /
--      legs / back) so the picker can render them under <optgroup>s.
-- =============================================================================
insert into exercises (name, video_url, section_types, subcategory) values

  -- ---- Strength · Chest ----
  ('Barbell bench press',           'https://www.youtube.com/shorts/i-gLOirnPaU',                           ARRAY['strength']::section_type[], 'chest'),
  ('Dumbell flat bench press',      'https://www.youtube.com/watch?v=xphvjGDZeYE',                           ARRAY['strength']::section_type[], 'chest'),
  ('Incline dumbell bench press',   'https://www.youtube.com/watch?v=0G2_XV7slIg',                           ARRAY['strength']::section_type[], 'chest'),
  ('Pec flies machine',             'https://www.youtube.com/watch?v=H4mVGHaK2f4',                           ARRAY['strength']::section_type[], 'chest'),
  ('Pec flies DB',                  'https://www.youtube.com/watch?v=QENKPHhQVi4',                           ARRAY['strength']::section_type[], 'chest'),
  ('Push ups',                      'https://www.youtube.com/watch?v=i9sTjhN4Z3M',                           ARRAY['strength']::section_type[], 'chest'),
  ('Plyometric push ups',           'https://www.youtube.com/watch?v=Y-uF4F3mQIs',                           ARRAY['strength']::section_type[], 'chest'),
  ('Incline push ups',              'https://www.youtube.com/watch?v=cfns5VDVVvk',                           ARRAY['strength']::section_type[], 'chest'),
  ('Deficite push ups',             'https://www.youtube.com/watch?v=kdOh9nQmioQ',                           ARRAY['strength']::section_type[], 'chest'),
  ('Cable flies',                   null,                                                                    ARRAY['strength']::section_type[], 'chest'),
  ('Single arm DB press',           null,                                                                    ARRAY['strength']::section_type[], 'chest'),
  ('DB 1.5 Press',                  null,                                                                    ARRAY['strength']::section_type[], 'chest'),
  ('DB floor press',                null,                                                                    ARRAY['strength']::section_type[], 'chest'),
  ('Hex press',                     'https://www.youtube.com/watch?v=MjOeSCRwAQY',                           ARRAY['strength']::section_type[], 'chest'),

  -- ---- Strength · Shoulders ----
  ('Barbell military press',        'https://www.youtube.com/watch?v=2yjwXTZQDDI&t=1s',                      ARRAY['strength']::section_type[], 'shoulders'),
  ('Seated DB shoulder press',      'https://www.youtube.com/watch?v=qEwKCR5JCog',                           ARRAY['strength']::section_type[], 'shoulders'),
  ('L sit DB hammer press',         'https://www.youtube.com/watch?v=VKAVy-3bDEQ',                           ARRAY['strength']::section_type[], 'shoulders'),
  ('Cable face pulls',              'https://www.youtube.com/watch?v=V8dZ3pyiCBo',                           ARRAY['strength']::section_type[], 'shoulders'),
  ('Barbell upright row',           'https://www.youtube.com/watch?v=v56LkVyOpzk',                           ARRAY['strength']::section_type[], 'shoulders'),
  ('DB upright row',                'https://www.youtube.com/watch?v=fy-Ou88ruAk',                           ARRAY['strength']::section_type[], 'shoulders'),
  ('DB Front raise',                null,                                                                    ARRAY['strength']::section_type[], 'shoulders'),
  ('DB lateral raise',              'https://www.youtube.com/watch?v=pKEdOuY4Ayg',                           ARRAY['strength']::section_type[], 'shoulders'),
  ('Chest supported rear delt flies', null,                                                                  ARRAY['strength']::section_type[], 'shoulders'),
  ('Rear delt fly machine',         'https://www.youtube.com/watch?v=JL8nHvZcAK8',                           ARRAY['strength']::section_type[], 'shoulders'),
  ('Plate front raises',            'https://www.youtube.com/watch?v=v7tac1hXOfU',                           ARRAY['strength']::section_type[], 'shoulders'),
  ('Half kneeling hammer press',    'https://www.youtube.com/watch?v=-tqKknpEk5g',                           ARRAY['strength']::section_type[], 'shoulders'),
  ('Half kneeling landmine press',  'https://www.youtube.com/watch?v=ORoOn93dnh4',                           ARRAY['strength']::section_type[], 'shoulders'),
  ('DB push press',                 null,                                                                    ARRAY['strength']::section_type[], 'shoulders'),
  ('Standing DB strict press',      null,                                                                    ARRAY['strength']::section_type[], 'shoulders'),
  ('Standing landmine press',       'https://youtu.be/5Cs27w8WVz4',                                          ARRAY['strength']::section_type[], 'shoulders'),

  -- ---- Strength · Arms ----
  ('Barbell curls',                 'https://www.youtube.com/watch?v=OoGO8UTHTcY',                           ARRAY['strength']::section_type[], 'arms'),
  ('Standing DB curls',             'https://www.youtube.com/watch?v=HnHuhf4hEWY',                           ARRAY['strength']::section_type[], 'arms'),
  ('Seated DB curls',               'https://www.youtube.com/watch?v=wSA84j9ZG4c',                           ARRAY['strength']::section_type[], 'arms'),
  ('DB hammer curls',               'https://www.youtube.com/watch?v=jQ-ksIi6edY',                           ARRAY['strength']::section_type[], 'arms'),
  ('Seated DB hammer curls',        'https://www.youtube.com/watch?v=kUZSOY0ev_s',                           ARRAY['strength']::section_type[], 'arms'),
  ('Cable curls',                   'https://www.youtube.com/shorts/vDmFPqGxFDQ',                            ARRAY['strength']::section_type[], 'arms'),
  ('Rope curls',                    'https://www.youtube.com/watch?v=INms4j4rz-A',                           ARRAY['strength']::section_type[], 'arms'),
  ('Parallell bar dips',            'https://www.youtube.com/watch?v=dX_nSOOJIsE',                           ARRAY['strength']::section_type[], 'arms'),
  ('Barbell skull crushers',        'https://www.youtube.com/shorts/9wJVCuSM0I4',                            ARRAY['strength']::section_type[], 'arms'),
  ('DB skull crushers',             'https://www.youtube.com/watch?v=tNeZvc-sknI',                           ARRAY['strength']::section_type[], 'arms'),
  ('Close grip bench press',        'https://www.youtube.com/watch?v=s5NGH5yyDcg',                           ARRAY['strength']::section_type[], 'arms'),
  ('Overhead DB extensions',        'https://www.youtube.com/watch?v=UO394dtzKRE',                           ARRAY['strength']::section_type[], 'arms'),
  ('Close grip push ups',           'https://www.youtube.com/watch?v=ABi1Z1Gc9Tw',                           ARRAY['strength']::section_type[], 'arms'),
  ('Rope push downs',               'https://www.youtube.com/watch?v=y6EdXBdL75A',                           ARRAY['strength']::section_type[], 'arms'),
  ('Cable push downs',              'https://www.youtube.com/shorts/e0FrR9V0HEI',                            ARRAY['strength']::section_type[], 'arms'),
  ('Bench tricep push downs',       'https://www.youtube.com/watch?v=JrHc1FBtVvM',                           ARRAY['strength']::section_type[], 'arms'),
  ('Weighted bench tricep push downs', 'https://www.youtube.com/watch?v=egQiO0K-BEw',                        ARRAY['strength']::section_type[], 'arms'),
  ('Tricep dips',                   'https://www.youtube.com/watch?v=6MwtkyNC2ZY',                           ARRAY['strength']::section_type[], 'arms'),
  ('Banded tricep push downs',      'https://www.youtube.com/watch?v=xW8L2POShSA',                           ARRAY['strength']::section_type[], 'arms'),
  ('Rope overhead extensions',      'https://www.youtube.com/watch?v=MegBRxtR14I',                           ARRAY['strength']::section_type[], 'arms'),

  -- ---- Strength · Legs ----
  ('Barbell back squat',            'https://www.youtube.com/shorts/gslEzVggur8',                            ARRAY['strength']::section_type[], 'legs'),
  ('Bodyweight squat',              'https://www.youtube.com/watch?v=fKOXaTFVGho',                           ARRAY['strength']::section_type[], 'legs'),
  ('Front squat',                   'https://www.youtube.com/watch?v=wyDbagKS7Rg',                           ARRAY['strength']::section_type[], 'legs'),
  ('DB goblet squat',               'https://www.youtube.com/watch?v=a-dqF4NL2K4',                           ARRAY['strength']::section_type[], 'legs'),
  ('Single leg leg press',          'https://www.youtube.com/watch?v=BsOg0iBKs6A',                           ARRAY['strength']::section_type[], 'legs'),
  ('Leg press',                     'https://www.youtube.com/watch?v=qCR9bN3G1t4',                           ARRAY['strength']::section_type[], 'legs'),
  ('Front DB lunge',                'https://www.youtube.com/watch?v=LEKGw5pKz1w',                           ARRAY['strength']::section_type[], 'legs'),
  ('Reverse DB lunge',              'https://www.youtube.com/watch?v=PFwB_6NWP60',                           ARRAY['strength']::section_type[], 'legs'),
  ('Front barbell lunge',           'https://www.youtube.com/watch?v=ci4rsmlOk24',                           ARRAY['strength']::section_type[], 'legs'),
  ('Reverse barbell lunge',         'https://www.youtube.com/watch?v=Xct7MsKO3fI',                           ARRAY['strength']::section_type[], 'legs'),
  ('Barbell split squat',           'https://www.youtube.com/watch?v=KXUJxb8hO8U',                           ARRAY['strength']::section_type[], 'legs'),
  ('DB split squat',                'https://www.youtube.com/watch?v=JNBgvZW2eR0',                           ARRAY['strength']::section_type[], 'legs'),
  ('Front foot elevated DB R lunge', 'https://www.youtube.com/watch?v=L80de7G3kBU',                          ARRAY['strength']::section_type[], 'legs'),
  ('Front foot elevated BB R lunge', 'https://www.youtube.com/watch?v=G2wviOTR4H0',                          ARRAY['strength']::section_type[], 'legs'),
  ('Leg extension machine',         'https://www.youtube.com/watch?v=IqUhWKkpub8',                           ARRAY['strength']::section_type[], 'legs'),
  ('Barbell hip thrust',            'https://www.youtube.com/watch?v=Zp26q4BY5HE',                           ARRAY['strength']::section_type[], 'legs'),
  ('Hip thrust machine',            'https://www.youtube.com/watch?v=amcaUtVnjkY',                           ARRAY['strength']::section_type[], 'legs'),
  ('Single leg glute bridge',       'https://www.youtube.com/watch?v=sXNqHp39o1U',                           ARRAY['strength']::section_type[], 'legs'),
  ('Single leg KB Hip thrust',      null,                                                                    ARRAY['strength']::section_type[], 'legs'),
  ('Barbell RDL',                   'https://www.youtube.com/shorts/5rIqP63yWFg',                            ARRAY['strength']::section_type[], 'legs'),
  ('DB RDL',                        'https://www.youtube.com/shorts/4M3CtvpM9xI',                            ARRAY['strength']::section_type[], 'legs'),
  ('Single leg DB RDL',             'https://www.youtube.com/watch?v=miFV8SN_85U',                           ARRAY['strength']::section_type[], 'legs'),
  ('Staggered Barbell RDL',         'https://www.youtube.com/watch?v=OyULrfC5etY',                           ARRAY['strength']::section_type[], 'legs'),
  ('Staggered DB RDL',              'https://www.youtube.com/watch?v=Th4QdA2BOyg',                           ARRAY['strength']::section_type[], 'legs'),
  ('Seated hamstring curl machine', 'https://www.youtube.com/watch?v=F488k67BTNo',                           ARRAY['strength']::section_type[], 'legs'),
  ('Lying hamstring curl machine',  'https://www.youtube.com/watch?v=bvs-Y_qgghE',                           ARRAY['strength']::section_type[], 'legs'),
  ('Standing calf raises',          'https://www.youtube.com/watch?v=kctJC4hCOD8',                           ARRAY['strength']::section_type[], 'legs'),
  ('Smith machine calf raises',     null,                                                                    ARRAY['strength']::section_type[], 'legs'),
  ('Seated calf raise machine',     'https://www.youtube.com/watch?v=JbyjNymZOt0',                           ARRAY['strength']::section_type[], 'legs'),
  ('Kettlebell swings',             'https://www.youtube.com/watch?v=YSxHifyI6s8&t=28s',                     ARRAY['strength']::section_type[], 'legs'),
  ('Barbell deadlifts',             'https://www.youtube.com/shorts/vfKwjT5-86k',                            ARRAY['strength']::section_type[], 'legs'),
  ('Trapbar deadlift',              'https://www.youtube.com/watch?v=WzvsIU9FW60&t=43s',                     ARRAY['strength']::section_type[], 'legs'),
  ('DB bulgarian split squats',     'https://www.youtube.com/shorts/uODWo4YqbT8',                            ARRAY['strength']::section_type[], 'legs'),
  ('Weighted knee over toe',        'https://www.youtube.com/shorts/v1_FWNirlwY',                            ARRAY['strength']::section_type[], 'legs'),
  ('Landmine squats',               'https://www.youtube.com/watch?v=_mfORB47xMs',                           ARRAY['strength']::section_type[], 'legs'),
  ('Suitcase cyclist squats',       'https://www.youtube.com/shorts/ILMr34Q1nHo',                            ARRAY['strength']::section_type[], 'legs'),
  ('Prisoner step ups',             'https://youtu.be/wMd5ZQxoY-o',                                          ARRAY['strength']::section_type[], 'legs'),
  ('Hamstring bridge holds',        'https://www.youtube.com/watch?v=BsMuoPOGUNQ',                           ARRAY['strength']::section_type[], 'legs'),
  ('Box step ups',                  'https://www.youtube.com/watch?v=PRKy_xYK0HA',                           ARRAY['strength']::section_type[], 'legs'),

  -- ---- Strength · Back ----
  ('Pendlay barbell row',           'https://www.youtube.com/watch?v=h4nkoayPFWw',                           ARRAY['strength']::section_type[], 'back'),
  ('Bent over barbell row',         'https://www.youtube.com/watch?v=yElnUE0j390',                           ARRAY['strength']::section_type[], 'back'),
  ('Supinated Barbell row',         'https://www.youtube.com/watch?v=uJ3ENVHRWEs',                           ARRAY['strength']::section_type[], 'back'),
  ('Bent over DB row',              'https://www.youtube.com/watch?v=mYDrddj3fj8',                           ARRAY['strength']::section_type[], 'back'),
  ('Single arm DB row',             'https://www.youtube.com/watch?v=RpODPuNtZS8',                           ARRAY['strength']::section_type[], 'back'),
  ('Chest supported DB row',        'https://www.youtube.com/watch?v=H75im9fAUMc',                           ARRAY['strength']::section_type[], 'back'),
  ('Single arm cable row',          'https://www.youtube.com/watch?v=0pGi67ADMRg',                           ARRAY['strength']::section_type[], 'back'),
  ('Chin ups',                      'https://www.youtube.com/watch?v=zmTsgGZy9oY',                           ARRAY['strength']::section_type[], 'back'),
  ('Band Assissted chin ups',       null,                                                                    ARRAY['strength']::section_type[], 'back'),
  ('Chin up negatives',             'https://www.youtube.com/watch?v=dJXAuZ5oIVQ',                           ARRAY['strength']::section_type[], 'back'),
  ('Wide grip lat pull down machine',  'https://www.youtube.com/watch?v=lueEJGjTuPQ',                        ARRAY['strength']::section_type[], 'back'),
  ('Close grip lat pull down machine', 'https://www.youtube.com/watch?v=8hzVLzu-RJk',                        ARRAY['strength']::section_type[], 'back'),
  ('Back hyper extensions',         'https://www.youtube.com/watch?v=ph3pddpKzzw',                           ARRAY['strength']::section_type[], 'back'),
  ('Neutral grip machine row',      'https://www.youtube.com/watch?v=TeFo51Q_Nsc',                           ARRAY['strength']::section_type[], 'back'),
  ('Inverted row',                  'https://www.youtube.com/shorts/j38Tn6vYhCM',                            ARRAY['strength']::section_type[], 'back'),
  ('KB Gorilla row',                null,                                                                    ARRAY['strength']::section_type[], 'back'),
  ('Renegade row',                  'https://www.youtube.com/watch?v=Lxb3FWMk6tg',                           ARRAY['strength']::section_type[], 'back'),

  -- ---- Conditioning ----
  ('DB thrusters',                  'https://www.youtube.com/watch?v=VdPjfmRcQfw',                           ARRAY['conditioning']::section_type[], null),
  ('Plate G2OH',                    'https://www.youtube.com/shorts/U3x_-pSUvXA',                            ARRAY['conditioning']::section_type[], null),
  ('DB snatches',                   'https://www.youtube.com/watch?v=mx8mr0xV8L0',                           ARRAY['conditioning']::section_type[], null),
  ('Burpees',                       'https://www.youtube.com/watch?v=TU8QYVW0gDU',                           ARRAY['conditioning']::section_type[], null),
  ('Down ups',                      'https://www.youtube.com/watch?v=4NRFUKgNhs8',                           ARRAY['conditioning']::section_type[], null),
  ('AKBS',                          'https://www.youtube.com/watch?v=bPtArDeLZjc',                           ARRAY['conditioning']::section_type[], null),
  ('DB deadlifts',                  'https://www.youtube.com/watch?v=JNpUNRPQkAk',                           ARRAY['conditioning']::section_type[], null),
  ('DB cleans',                     'https://www.youtube.com/watch?v=MmcHmvGzEUQ',                           ARRAY['conditioning']::section_type[], null),
  ('DB clean and press',            'https://www.youtube.com/watch?v=2YedyLmkDRE',                           ARRAY['conditioning']::section_type[], null),
  ('Ski erg',                       'https://www.youtube.com/watch?v=B0lIgT5PHc8',                           ARRAY['conditioning']::section_type[], null),
  ('Rowing machine',                'https://www.youtube.com/watch?v=4zWu1yuJ0_g',                           ARRAY['conditioning']::section_type[], null),
  ('Dual DB devil press',           'https://www.youtube.com/watch?v=zlqEtAUds-I',                           ARRAY['conditioning']::section_type[], null),
  ('Single DB devils press',        'https://www.youtube.com/shorts/zCrgj9pbWas',                            ARRAY['conditioning']::section_type[], null),

  -- ---- Plyometrics (plyo) ----
  ('Box jumps',                     'https://www.youtube.com/watch?v=NBY9-kTuHEk',                           ARRAY['plyo']::section_type[], null),
  ('Seated box jumps',              'https://www.youtube.com/watch?v=64OAo8kINPQ',                           ARRAY['plyo']::section_type[], null),
  ('Lateral jumps',                 'https://www.youtube.com/watch?v=soqQy4dzEts',                           ARRAY['plyo']::section_type[], null),
  ('Calf pogos',                    'https://www.youtube.com/watch?v=HEIFixqLvA0',                           ARRAY['plyo']::section_type[], null),
  ('Depth jumps',                   'https://www.youtube.com/watch?v=DxzbXy0lC6Y',                           ARRAY['plyo']::section_type[], null),
  ('Drop jumps',                    'https://youtube.com/shorts/3ODQAlh-Xj8',                                ARRAY['plyo']::section_type[], null),
  ('Banded overspeed jumps',        null,                                                                    ARRAY['plyo']::section_type[], null),
  ('Countermovement jump',          'https://www.youtube.com/watch?v=1MrrWNWLjUc',                           ARRAY['plyo']::section_type[], null),
  ('Weighted counter movement jump', 'https://www.youtube.com/watch?v=_XTsyh4-b-M',                          ARRAY['plyo']::section_type[], null),
  ('Box squats',                    'https://www.youtube.com/watch?v=FsGNk8Z74FE',                           ARRAY['plyo']::section_type[], null),
  ('Barbell cleans',                'https://www.youtube.com/watch?v=KjGvwQl8tis',                           ARRAY['plyo']::section_type[], null),
  ('Single leg box jumps',          'https://www.youtube.com/watch?v=LDU_yVvp7pA',                           ARRAY['plyo']::section_type[], null),
  ('Single leg depth jumps',        'https://www.youtube.com/watch?v=mUomlUZxaxA',                           ARRAY['plyo']::section_type[], null),
  ('Single leg drop jumps',         'https://www.youtube.com/watch?v=mUomlUZxaxA',                           ARRAY['plyo']::section_type[], null),
  ('Hip flexor tuck jumps',         'https://www.youtube.com/watch?v=QU7CAOBWAcY',                           ARRAY['plyo']::section_type[], null),
  ('Explosive box step ups',        'https://www.youtube.com/watch?v=KWZWv0tg8Z4',                           ARRAY['plyo']::section_type[], null),
  ('Med ball chest pass',           'https://www.youtube.com/watch?v=STC0aLAIl2g',                           ARRAY['plyo']::section_type[], null),
  ('Medicine ball side shuffle',    'https://www.youtube.com/watch?v=vXVRXXEWKdc',                           ARRAY['plyo']::section_type[], null),
  ('Plyo step ups',                 'https://www.youtube.com/shorts/Qox5zFrFPPM',                            ARRAY['plyo']::section_type[], null),
  ('Broad jumps',                   'https://www.youtube.com/watch?v=XqpN9AbLMe4',                           ARRAY['plyo']::section_type[], null),
  ('Single leg step up calf pogos', 'https://www.youtube.com/watch?v=NsTh_pESx5E',                           ARRAY['plyo']::section_type[], null),
  ('Triple broad jump',             'https://www.youtube.com/watch?v=CuXErkWUo1k',                           ARRAY['plyo']::section_type[], null),
  ('Trap bar jumps',                'https://www.youtube.com/shorts/BZNWtIIsrps',                            ARRAY['plyo']::section_type[], null),
  ('Approach box jump',             null,                                                                    ARRAY['plyo']::section_type[], null),
  ('Weighted skater jumps',         null,                                                                    ARRAY['plyo']::section_type[], null),
  ('Split stance pogos',            'https://www.youtube.com/shorts/CmBxpNFHKNE',                            ARRAY['plyo']::section_type[], null),
  ('Weighted snap down jumps',      'https://www.youtube.com/watch?v=omSLml7hPzw',                           ARRAY['plyo']::section_type[], null),
  ('No arm swing box jump',         null,                                                                    ARRAY['plyo']::section_type[], null),
  ('Banded lateral shuffles',       'https://www.youtube.com/shorts/b2IZYiMTldA',                            ARRAY['plyo']::section_type[], null),
  ('Seated rocker jumps',           null,                                                                    ARRAY['plyo']::section_type[], null),
  ('CMJ',                           null,                                                                    ARRAY['plyo']::section_type[], null),
  ('Explosive KPI''s',              null,                                                                    ARRAY['plyo']::section_type[], null),
  ('Explosive hex deadlifts',       null,                                                                    ARRAY['plyo']::section_type[], null),
  ('Pin squat',                     null,                                                                    ARRAY['plyo']::section_type[], null),
  ('Staggered pin squat',           null,                                                                    ARRAY['plyo']::section_type[], null),
  ('Elevated hex deadlift',         'https://www.youtube.com/watch?v=gj7w0PbgZ0w',                           ARRAY['plyo']::section_type[], null),
  ('Staggered hex deadlift',        null,                                                                    ARRAY['plyo']::section_type[], null),
  ('Banded deadlift',               null,                                                                    ARRAY['plyo']::section_type[], null),
  ('Loaded rocker jumps',           'https://www.youtube.com/watch?v=aGi8sJ4HKCY',                           ARRAY['plyo']::section_type[], null),
  ('Smith machine R lunge to knee drive', 'https://www.youtube.com/watch?v=NbN258PRmQI',                     ARRAY['plyo']::section_type[], null),
  ('DB step up with knee drive',    null,                                                                    ARRAY['plyo']::section_type[], null),
  ('Rotational landmine press',     null,                                                                    ARRAY['plyo']::section_type[], null),

  -- ---- Core conditioning ----
  ('Cable crunches',                'https://www.youtube.com/shorts/jurXt-aY4XY',                            ARRAY['core_conditioning']::section_type[], null),
  ('Butterfly sit ups',             'https://www.youtube.com/watch?v=O4_u-dOYBA0',                           ARRAY['core_conditioning']::section_type[], null),
  ('Decline sit ups',               'https://www.youtube.com/watch?v=IINnwHwexkg',                           ARRAY['core_conditioning']::section_type[], null),
  ('Russian twists',                'https://www.youtube.com/shorts/sKqCLk6qINs',                            ARRAY['core_conditioning']::section_type[], null),
  ('Cable wood chops',              'https://www.youtube.com/watch?v=ZDt4MCvjMAA',                           ARRAY['core_conditioning']::section_type[], null),
  ('Hanging Leg raises',            'https://www.youtube.com/watch?v=Nw0LOKe3_l8',                           ARRAY['core_conditioning']::section_type[], null),
  ('Knee tucks',                    'https://www.youtube.com/watch?v=KYwP30AD_h0',                           ARRAY['core_conditioning']::section_type[], null),
  ('Leg raises',                    'https://www.youtube.com/watch?v=q0JVBRHoLz4',                           ARRAY['core_conditioning']::section_type[], null),
  ('V ups',                         'https://www.youtube.com/watch?v=NxkukiEoh3g',                           ARRAY['core_conditioning']::section_type[], null),
  ('Medicine ball slams',           'https://www.youtube.com/watch?v=_94O_ylGCiw',                           ARRAY['core_conditioning']::section_type[], null),
  ('Kneeling ball slams',           'https://www.youtube.com/watch?v=qVqEkYRFPbo',                           ARRAY['core_conditioning']::section_type[], null),
  ('High plank db transfers',       'https://www.youtube.com/watch?v=Zko5x2SoQmo',                           ARRAY['core_conditioning']::section_type[], null),
  ('High plank',                    'https://www.youtube.com/watch?v=gLSCvAvvuFk',                           ARRAY['core_conditioning']::section_type[], null),
  ('Low plank',                     'https://www.youtube.com/watch?v=Iu1Tp-z2_KQ',                           ARRAY['core_conditioning']::section_type[], null),
  ('Bear hold',                     'https://www.youtube.com/watch?v=6OeNKSJhcv8',                           ARRAY['core_conditioning']::section_type[], null),
  ('Copenhagen plank',              'https://www.youtube.com/watch?v=py5T6E4lfg8',                           ARRAY['core_conditioning']::section_type[], null),
  ('Ab rollouts',                   'https://www.youtube.com/watch?v=rqiTPdK1c_I',                           ARRAY['core_conditioning']::section_type[], null),
  ('Landmine half moons',           'https://youtu.be/4dGj7rES9pY',                                          ARRAY['core_conditioning']::section_type[], null),
  ('Rock hollow holds',             'https://www.youtube.com/shorts/zYkNCoGJz7I',                            ARRAY['core_conditioning']::section_type[], null),
  ('Farmers carry',                 'https://www.youtube.com/watch?v=p5MNNosenJc',                           ARRAY['core_conditioning']::section_type[], null),
  ('Suitcase carry',                'https://www.youtube.com/shorts/4Fd97vmoLLk',                            ARRAY['core_conditioning']::section_type[], null),
  ('Straight leg sit ups',          'https://www.youtube.com/shorts/QqVL0YbKgWo',                            ARRAY['core_conditioning']::section_type[], null),
  ('Plate crunch transfers',        null,                                                                    ARRAY['core_conditioning']::section_type[], null),
  ('Bear hold transfers',           null,                                                                    ARRAY['core_conditioning']::section_type[], null),
  ('Weighted deadbugs',             null,                                                                    ARRAY['core_conditioning']::section_type[], null),
  ('High to low plank',             'https://www.youtube.com/shorts/44eOp4ZXckE',                            ARRAY['core_conditioning']::section_type[], null),
  ('Short lever copenhagen plank',  null,                                                                    ARRAY['core_conditioning']::section_type[], null),
  ('Toes to KB',                    null,                                                                    ARRAY['core_conditioning']::section_type[], null),

  -- ---- Primers / switch ons ----
  ('Glute bridge march',            'https://www.youtube.com/watch?v=c_4Y0I8vgzY&t=3s',                      ARRAY['prime']::section_type[], null),
  ('Swiss ball deadbug',            null,                                                                    ARRAY['prime']::section_type[], null),
  ('High plank shoulder taps',      'https://www.youtube.com/watch?v=v7S_KWW19hM',                           ARRAY['prime']::section_type[], null),
  ('Gorilla hold shoulder taps',    'https://www.youtube.com/watch?v=SGVDoTINUeI',                           ARRAY['prime']::section_type[], null),
  ('Rotate and press',              'https://www.youtube.com/watch?v=wEm2gr9SpIA',                           ARRAY['prime']::section_type[], null),
  ('Push up hold',                  'https://www.youtube.com/watch?v=pupwibLXtO8',                           ARRAY['prime']::section_type[], null),
  ('ATG split squat',               null,                                                                    ARRAY['prime']::section_type[], null),
  ('Full ROM calf raise',           'https://www.youtube.com/watch?v=Y-FN-LzJQr0',                           ARRAY['prime']::section_type[], null),
  ('Pendulum lunge',                'https://www.youtube.com/watch?v=LJTRp6rkjX8',                           ARRAY['prime']::section_type[], null),
  ('Weighted deep squat hold',      'https://www.youtube.com/watch?v=jrgGn08ZXsg',                           ARRAY['prime']::section_type[], null),
  ('Hyperextensions',               'https://www.youtube.com/shorts/RbibTrk_jFQ',                            ARRAY['prime']::section_type[], null),
  ('Inch worms',                    'https://www.youtube.com/watch?v=0HFXsIMKqUg',                           ARRAY['prime']::section_type[], null),
  ('TRX Row',                       null,                                                                    ARRAY['prime']::section_type[], null),
  ('Worlds greatest stretch',       'https://www.youtube.com/watch?v=nG38sH8fwSM',                           ARRAY['prime']::section_type[], null),
  ('DB Halos',                      'https://www.youtube.com/watch?v=E5PFmXskW30',                           ARRAY['prime']::section_type[], null),
  ('Banded pull aparts',            'https://www.youtube.com/watch?v=LoBBo1dtY6I',                           ARRAY['prime']::section_type[], null),
  ('Hip abductor side walks',       'https://www.youtube.com/watch?v=e_ehSxDmdU4',                           ARRAY['prime']::section_type[], null),
  ('Lunge with twist',              'https://www.youtube.com/watch?v=3hQEQIWgF9E',                           ARRAY['prime']::section_type[], null),
  ('Bird dogs',                     'https://www.youtube.com/watch?v=wiFNA3sqjCA',                           ARRAY['prime']::section_type[], null),
  ('Cat/cow',                       'https://www.youtube.com/watch?v=ESJ6Ghvgr6k',                           ARRAY['prime']::section_type[], null),
  ('Deadbugs',                      'https://www.youtube.com/watch?v=4XLEnwUr1d8',                           ARRAY['prime']::section_type[], null),
  ('Weighted dead bugs',            'https://www.youtube.com/watch?v=KGg28uDVIKw',                           ARRAY['prime']::section_type[], null),
  ('DB Y raises',                   'https://www.youtube.com/watch?v=wWhG-7CQQmg',                           ARRAY['prime']::section_type[], null),
  ('Pike toe touches',              'https://www.youtube.com/watch?v=KRZTx-fjuOA',                           ARRAY['prime']::section_type[], null),
  ('Banded crab walks',             'https://www.youtube.com/shorts/1wVVwBgA2AE',                            ARRAY['prime']::section_type[], null),
  ('Full range calf raises',        'https://www.youtube.com/shorts/yXPrslr4Bz4',                            ARRAY['prime']::section_type[], null),
  ('Split squat calf raise',        'https://www.youtube.com/watch?v=xQMVHF5IlGo',                           ARRAY['prime']::section_type[], null),
  ('Half kneeling soleus hold',     'https://www.youtube.com/watch?v=7bm0p0m7yk4',                           ARRAY['prime']::section_type[], null),
  ('Elevated soleus raises',        'https://www.youtube.com/shorts/dQv583TFW8A',                            ARRAY['prime']::section_type[], null),
  ('TRX squats',                    'https://www.youtube.com/watch?v=NM-Mqg4fZ3o',                           ARRAY['prime']::section_type[], null),
  ('Banded dislocates',             null,                                                                    ARRAY['prime']::section_type[], null),
  ('Hip aeroplanes',                null,                                                                    ARRAY['prime']::section_type[], null),
  ('Counter balance pistols',       'https://www.youtube.com/shorts/dYc-GdboMWg',                            ARRAY['prime']::section_type[], null),
  ('Glute bridge + pulse',          null,                                                                    ARRAY['prime']::section_type[], null),
  ('Upside down KB press',          null,                                                                    ARRAY['prime']::section_type[], null),
  ('Weighted toe walks',            null,                                                                    ARRAY['prime']::section_type[], null),
  ('Bottoms up KB press',           null,                                                                    ARRAY['prime']::section_type[], null),
  ('KB Hip lifts',                  'https://www.youtube.com/shorts/KoQrZsENTNQ',                            ARRAY['prime']::section_type[], null),
  ('R Lunge to step up',            'https://www.youtube.com/shorts/xjV5WZgmoY4',                            ARRAY['prime']::section_type[], null),
  ('Swiss ball curls',              null,                                                                    ARRAY['prime']::section_type[], null),
  ('Single leg hyper extensions',   null,                                                                    ARRAY['prime']::section_type[], null),
  ('Tib raises',                    null,                                                                    ARRAY['prime']::section_type[], null),
  ('Elevated glute bridge march',   null,                                                                    ARRAY['prime']::section_type[], null),
  ('Banded goodmornings',           'https://www.youtube.com/watch?v=fJA39ZOVaEQ',                           ARRAY['prime']::section_type[], null),
  ('Weighted IYT''s',               null,                                                                    ARRAY['prime']::section_type[], null),
  ('Kang squat',                    null,                                                                    ARRAY['prime']::section_type[], null),
  ('Weighted swimmers',             null,                                                                    ARRAY['prime']::section_type[], null),
  ('KB Hip flexor lift',            null,                                                                    ARRAY['prime']::section_type[], null),
  ('Goblet curtsey lunge',          null,                                                                    ARRAY['prime']::section_type[], null);
